### ISSUE TITLE
List main sources and put in sources table

### ISSUE THREAD

**Issue by rufuspollock** [okfn/dashboard#2]
Add them to [Sources gdoc](https://docs.google.com/spreadsheet/ccc?key=0Aon3JiuouxLUdEYzTzlyZy1Oc3oycGZ1RFNVaFUzbVE&hl=en_GB#gid=0). Process:
- For each project in [projects list](https://docs.google.com/spreadsheet/ccc?key=0Al6mO9_3Hr2PdGhHVDBCYmQ5QWN5ZDROLU9yMUswQVE&hl=en_GB#gid=0)
- Get list of sources of activity e.g. blog posts, code commits, wiki changes etc.
- For each of these add an entry to the [sources spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Aon3JiuouxLUdEYzTzlyZy1Oc3oycGZ1RFNVaFUzbVE&hl=en_GB#gid=0) following the structure suggested there

**Comment by DBishton** [comment]
Hi, I'd like to get started on this, but I need to know what constitutes a 'source' and where I find them so I can begin populating the table. Sorry if this is rather obvious. Thanks!

**Comment by DBishton** [comment]
OK, so I've listed the main sources from active projects (with the EXCEPTION of twitter feeds), and GitHub repositories from 'DPM' down to 'webstore'. I hope that makes sense!

**Comment by rufuspollock** [comment]
FIXED. Done during hackday several months ago.
