### ISSUE TITLE
Tests for JS code

### ISSUE THREAD

**Issue by rufuspollock** [okfn/dashboard#28]

**Comment by rufuspollock** [comment]
Done in 7b27ff2a94164dce3c8965f745675e05082479c4 (merge of @elemoine work)

**Comment by elemoine** [comment]
Quick note: headless testing (for continuous integration) should be possible with PhantomJS. See http://blog.ivandemarino.me/2011/07/09/Maven-PhantomJS-and-Jasmine-to-write-your-JS-Unit-Testing for example.
