### ISSUE TITLE
Reconciliation system for users referenced in activity

### ISSUE THREAD

**Issue by rufuspollock** [okfn/dashboard#3]
- Need to fill person_id field on activity.
- Should do this separately from activity creation (in a separate reconciliation process)

Proposed setup:
- Enter: author name to username matches into reconcilication table in gdocs
- Go through reconciling and add to activity table and new column called person_username that links to the person table username column

Questions:
- What happens if no person with that username (need to create a person)
- Dealing with anonymous stuff (leave username blank? create anonymous person)

**Comment by teajaymars** [comment]
This functionality will be handled in the backend of the [Activity API](https://github.com/okfn/activityapi), which maintains a PostgreSQL database of activity with multiple worker threads to pull in data and resolve it against `people`. See issue https://github.com/okfn/activityapi/issues/9.
