### ISSUE TITLE
Main mailing lists to highlight

### ISSUE THREAD

**Issue by noelmas** [okfn/dashboard#45]
- OKFN Announce - our main news and fundraising site linked to on the main site
- OKFN Discuss - general discussion about OKFN issues

Not sure of the value of having OKFN Help or OKFN Coord there...

**Comment by noelmas** [comment]
Ah yes and to be clear - OKFN Announce is now run off Mailchimp, I hope you can use their API...

Ping me for log-in so you can get the key...

**Comment by teajaymars** [comment]
See #54 for the latest on this
