### ISSUE TITLE
Check out Crowdbooster

### ISSUE THREAD

**Issue by teajaymars** [okfn/dashboard#47]
We've got some historic snapshots of interesting social networking data in Crowdbooster.

There's no API, so we can't feed off this source directly. But we could pull out the historic data and track these metrics (in particular, Facebook) ourselves.

I'm just saying: Before writing this all from scratch, check out how Crowdbooster have done it to minimise reinvention. Community team just want a couple of key metrics in one place, and Crowdbooster is not a very Open place to have all that.

**Comment by noelmas** [comment]
Also, I dislike Crowdbooster UI - the Dashboard is far better for a clear snapshot of what's going on

**Comment by teajaymars** [comment]
Cool. We can't rebuild retweet/influence tracking but the raw Twitter metrics we have. I've extracted Crowdbooster's analysis of our Facebook likes, too, and that'll go into #46
