### ISSUE TITLE
Cron jobs to pull github info seem to be failing

### ISSUE THREAD

**Issue by rufuspollock** [okfn/dashboard#49]
See e.g. http://okfnlabs.org/dashboard/#project/ckan which does not have November data ...

**Comment by rufuspollock** [comment]
@zephod any details here?

**Comment by teajaymars** [comment]
The fix you pushed in mid-jan is totally adequate here!

**Comment by rufuspollock** [comment]
My bad for not closing. Renames of repos is still a PITA but not much we can do i think ...
