### ISSUE TITLE
Convert geonames data to a geojson object

### ISSUE THREAD

**Issue by rufuspollock** [okfn/dashboard#7]
Rather than storing geonames data in members.py store a geojson object (see http://geojson.org/geojson-spec.html). Suggest:

<pre>
{
  type: "Feature",
  geometry:  {"type": "Point", "coordinates": [geonames.lng,  geonames.lat]},
  properties: {
    label: geoname-name,
    geonameId: geonames.geonameId
  } 
}

**Comment by seanh** [comment]
Looking at this now...

**Comment by seanh** [comment]
Ignore my first commit above (contained some unwanted stuff), the second commit is good
